### ISSUE TITLE
Image is not transparent.

### ISSUE THREAD

**Issue by CodingSpecies** [Polar-69/Polar-Chat#1]
@Polar-69 the image at the top of your chat has lines drawn over it, making it not transparent:
<img src="https://polar-chatty.polar-69.repl.co/img/logo.png" height=200 />

I like the chat design, and the chat itself, but I think the image quality is not up to the rest of the app's standards. If you would like, please can you assign me to this issue, so I can work on it? Thank you.

**Comment by Polar-69** [comment]
thanks for lettign me know i might change logo, will take jsut a sec and one file change but from the looks of it it looks mostly transparent
